In [36]:
import selenium
import pandas as pd
from selenium import webdriver
import time
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from bs4 import BeautifulSoup
import requests
import re

# 1

In [2]:
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(3)

In [3]:
url = "https://www.amazon.in/"
driver.get(url)

In [4]:
time.sleep(2)
user_inp = input('Enter the product you want to search : ')

Enter the product you want to search : guitar

In [5]:
search_bar = driver.find_element_by_id("twotabsearchtextbox")    
search_bar.clear()                                               
search_bar.send_keys(user_inp)                                 
search_button = driver.find_element_by_xpath('//div[@class="nav-search-submit nav-sprite"]/span/input')       
search_button.click()

# 2

In [6]:
product_urls = []
start=0
end=3
for page in range(start,end):
    url=driver.find_elements_by_xpath('//a[@class="a-link-normal a-text-normal"]')       
    for i in url:
        product_urls.append(i.get_attribute("href"))                       
    nxt_button=driver.find_element_by_xpath("//li[@class='a-last']//a")   
    nxt_button.click()
    time.sleep(2)

In [7]:
Brand = []   
Name = []
Rating = []
no_of_ratings = []
Price = []
Return = []
expected_delivery = []
Availability = [] 
Other_Details = []

In [8]:
for url in product_urls:
    driver.get(url)
    time.sleep(2)

In [11]:
try:
        brand = driver.find_element_by_xpath('//a[@id="bylineInfo"]')      
        Brand.append(brand.text)
except NoSuchElementException:
        Brand.append('-')

In [12]:

    time.sleep(1)
    # Extracting name from id
    try:
        name = driver.find_element_by_id('productTitle')      
        Name.append(name.text)
    except NoSuchElementException:
        Name.append('-')

In [14]:
 time.sleep(1)    
    # Extracting Ratings from xpath    
try:
        rating = driver.find_element_by_xpath('//span[@class="a-size-base a-nowrap"]//span')  
        Rating.append(rating.text)
except NoSuchElementException:
        Rating.append('-')

In [15]:
time.sleep(1)
    # Extracting No of Ratings from xpath
try:
        no_rating = driver.find_element_by_xpath('//span[@class="a-size-base a-color-secondary"]')  
        no_of_ratings.append(no_rating.text)
except NoSuchElementException:
        no_of_ratings.append('-')

In [18]:
time.sleep(1)
    # Extracting price from xpath    
try:
        price = driver.find_element_by_xpath('//td[@class="a-span12"]')  
        Price.append(price.text)
except NoSuchElementException:
        Price.append('-')

In [19]:
 time.sleep(1)
    # Extracting Return from xpath
try:
        return_ = driver.find_element_by_xpath('//a[@class="a-size-small a-link-normal a-text-normal"]')  
        Return.append(return_.text)
except NoSuchElementException:
        Return.append('-')

In [21]:
time.sleep(1)
    # Extracting expected_delivery from xpath
try:
        exptd_dlvry= driver.find_element_by_xpath('//span[@class="a-color-error"]')  
        expected_delivery.append(exptd_dlvry.text)
except NoSuchElementException:
         expected_delivery.append('-')

In [22]:
time.sleep(1)
    # Extracting Availability from xpath         
try:
        avl= driver.find_element_by_xpath('//span[@class="a-size-medium a-color-success"]')  
        Availability.append(avl.text)
except NoSuchElementException:
        Availability.append('-')

In [23]:
time.sleep(1)
    # Extracting Other Details from xpath    
try:
        othr_dtls= driver.find_element_by_xpath('//ul[@class="a-unordered-list a-vertical a-spacing-mini"]')  
        Other_Details.append(othr_dtls.text)
except NoSuchElementException:
        Other_Details.append('-')

In [26]:
time.sleep(2)    
a = {'Brand':Brand,'Name':Name,'Rating':Rating,'No. of ratings':no_of_ratings,'Price':Price,
                        'Return/Exchange':Return,'Expected Delivery':expected_delivery,'Availability':Availability,
                        'Other Details':Other_Details,'URL':product_urls}

In [27]:
df = pd.DataFrame.from_dict(a, orient='index')
df = df.transpose()

In [28]:
df.head(5)

,Brand,Name,Rating,No. of ratings,Price,Return/Exchange,Expected Delivery,Availability,Other Details,URL
0,Visit the Kadence Store,Kadence Acoustica Series Semi Acoustic Ash Woo...,3.9 out of 5,Total price:,"â‚¹ 7,199.00",Pay on Delivery,-,In stock.,Product Type : Acoustic Guitar Fretboard mater...,https://www.amazon.in/gp/slredirect/picassoRed...
1,None,None,None,None,None,None,None,None,None,https://www.amazon.in/gp/slredirect/picassoRed...
2,None,None,None,None,None,None,None,None,None,https://www.amazon.in/gp/slredirect/picassoRed...
3,None,None,None,None,None,None,None,None,None,https://www.amazon.in/gp/slredirect/picassoRed...
4,None,None,None,None,None,None,None,None,None,https://www.amazon.in/Juarez-Acoustic-Cutaway-...

# 3.

In [29]:
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(3)

In [30]:
url = "https://images.google.com/"
driver.get(url)

In [31]:
search_bar = driver.find_element_by_xpath('//*[@id="sbtc"]/div/div[2]/input')    # Finding the search bar using it's xpath
search_bar.send_keys("fruits")       # Inputing "banana" keyword to search rock images
search_button = driver.find_element_by_xpath('//*[@id="sbtc"]/button')    # Finding the xpath of search button
search_button.click()

In [32]:
for _ in range(500):
    driver.execute_script("window.scrollBy(0,10000)")
    
images = driver.find_elements_by_xpath('//img[@class="rg_i Q4LuWd"]')

In [33]:
img_urls = []
img_data = []
for image in images:
    source= image.get_attribute('src')
    if source is not None:
        if(source[0:4] == 'http'):
            img_urls.append(source)

In [34]:
for i in range(len(img_urls)):
    if i >= 100:
        break
    print("Downloading {0} of {1} images" .format(i, 100))
    response= requests.get(img_urls[i])
    file = open(r"G:\Fliprobo data\fliprobo images\fruits"+str(i)+".jpg", "wb")
    file.write(response.content)

# 4

In [35]:
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(3)

# opning flipkart.com
driver.get('https://www.flipkart.com/')
time.sleep(3)
try:
    login_X_button = driver.find_element_by_xpath('//button[@class="_2KpZ6l _2doB4z"]')                      # Button to close login popup
    login_X_button.click()
except NoSuchElementException : 
    print("No Login page")
search_bar = driver.find_element_by_xpath('//*[@id="container"]/div/div[1]/div[1]/div[2]/div[2]/form/div/div/input')    # Finding the search bar using it's xpath
search_bar.clear()               # Clearing the search bar
search_bar.send_keys("pixel")       # Inputing keyword to search
search_button = driver.find_element_by_xpath('//button[@class="L0Z3Pu"]')    # Finding the xpath of search button
search_button.click()        # Clicking the search button

In [36]:
flip_urls = []
urls = driver.find_elements_by_xpath('//a[@class="_1fQZEK"]')
for url in urls:
    flip_urls.append(url.get_attribute("href"))

In [37]:
flip_dict = {}
flip_dict["Brand"] = []
flip_dict["Smartphone"] = []
flip_dict["Colour"] = []
flip_dict["RAM"] = []
flip_dict["Storage(ROM)"] = []
flip_dict["Primary Camera"] = []
flip_dict["Secondary Camera"] = []
flip_dict["Display Size"] = []
flip_dict["Display Resolution"] = []
flip_dict["Processor"] = []
flip_dict["Processor Cores"] = []
flip_dict["Battery Capacity"] = []
flip_dict["Battery Type"] = []
flip_dict["Price"] = []
flip_dict["URL"] = []

In [38]:
for url in flip_urls:
    driver.get(url)    # Saving url                                                     
    print("Scraping URL = ", url)
    flip_dict['URL'].append(url)                                                          # Loading the webpage by url
    time.sleep(2)

In [39]:
try:
        read_more = driver.find_element_by_xpath('//button[@class="_2KpZ6l _1FH0tX"]')     # Button for expanding the specs
        read_more.click()
except NoSuchElementException:
        print("Exception Occured. Moving to next page")

Exception Occured. Moving to next page

In [40]:
try:
        brand = driver.find_element_by_xpath('//span[@class="B_NuCI"]')      # Extracting Brand from xpath
        flip_dict["Brand"].append(brand.text.split()[0])
except NoSuchElementException:
        flip_dict['Brand'].append('-')

In [41]:
try:
        price = driver.find_element_by_xpath('//div[@class="_30jeq3 _16Jk6d"]')      # Extracting Price from xpath
        flip_dict['Price'].append(price.text)
except NoSuchElementException:
        flip_dict['Price'].append('-')

In [42]:
try:
        name = driver.find_element_by_xpath('//div[@class="_3k-BhJ"][1]/table/tbody/tr[3]/td[2]/ul/li')      # Extracting Name from xpath
        flip_dict['Smartphone'].append(name.text)
except NoSuchElementException:
        flip_dict['Smartphone'].append('-')

In [43]:
try:
        color = driver.find_element_by_xpath('//div[@class="_3k-BhJ"][1]/table/tbody/tr[4]/td[2]/ul/li')      # Extracting colour from xpath
        flip_dict['Colour'].append(color.text)
except NoSuchElementException:
        flip_dict['Colour'].append('-')

In [44]:
try:
        disp_chk = driver.find_element_by_xpath('//div[@class="_3k-BhJ"][2]/div')
        if disp_chk.text != "Display Features" : raise NoSuchElementException
        disp_size = driver.find_element_by_xpath('//div[@class="_3k-BhJ"][2]/table[1]/tbody/tr[1]/td[2]/ul/li')  # Extracting Display Size from xpath
        flip_dict['Display Size'].append(disp_size.text)
except NoSuchElementException:
        flip_dict['Display Size'].append('-')

In [45]:
try:
        disp_chk = driver.find_element_by_xpath('//div[@class="_3k-BhJ"][2]/div')
        if disp_chk.text != "Display Features" : raise NoSuchElementException
        disp_res = driver.find_element_by_xpath('//div[@class="_3k-BhJ"][2]/table[1]/tbody/tr[2]/td[2]/ul/li')     # Extracting Display Resolution from xpath
        flip_dict['Display Resolution'].append(disp_res.text)
except NoSuchElementException:
        flip_dict['Display Resolution'].append('-')

In [93]:
 try:                                                                                     # Extracting Processor Cores from xpath
        core_chk = driver.find_element_by_xpath('//div[@class="_3k-BhJ"][3]/table[1]/tbody/tr[3]/td[1]')
        if core_chk.text != "Processor Core" :
            core_chk = driver.find_element_by_xpath('//div[@class="_3k-BhJ"][3]/table[1]/tbody/tr[2]/td[1]')
            if core_chk.text != "Processor Core" : 
                raise NoSuchElementException
            else :
                cores = driver.find_element_by_xpath('//div[@class="_3k-BhJ"][3]/table[1]/tbody/tr[2]/td[2]/ul/li')
        else :
            cores = driver.find_element_by_xpath('//div[@class="_3k-BhJ"][3]/table[1]/tbody/tr[3]/td[2]/ul/li')
        flip_dict['Processor Cores'].append(cores.text)
except NoSuchElementException:
        flip_dict['Processor Cores'].append('-')

In [52]:
try:
        rom = driver.find_element_by_xpath('//div[@class="_3k-BhJ"][4]/table[1]/tbody/tr[1]/td[2]/ul/li')         # Extracting Storage(ROM) from xpath
        flip_dict['Storage(ROM)'].append(rom.text)
except NoSuchElementException:
        flip_dict['Storage(ROM)'].append('-')

In [53]:
try:
        ram = driver.find_element_by_xpath('//div[@class="_3k-BhJ"][4]/table[1]/tbody/tr[2]/td[2]/ul/li')                # Extracting RAM from xpath
        flip_dict['RAM'].append(ram.text)
except NoSuchElementException:
        flip_dict['RAM'].append('-')

In [54]:
try:                                                                                  
        pri_cam = driver.find_element_by_xpath('//div[@class="_3k-BhJ"][5]/table[1]/tbody/tr[2]/td[2]/ul/li')     # Extracting Camera from xpath
        flip_dict['Primary Camera'].append(pri_cam.text)
except NoSuchElementException:
        flip_dict['Primary Camera'].append('-')

In [79]:
 try:                                                                                    # Extracting Secondary Camera from xpath
        cam_chk = driver.find_element_by_xpath('//div[@class="_3k-BhJ"][5]/table[1]/tbody/tr[6]/td[1]')
        if cam_chk != "Secondary Camera" : 
            if driver.find_element_by_xpath('//div[@class="_3k-BhJ"][5]/table[1]/tbody/tr[5]/td[1]').text == "Secondary Camera":
                sec_cam = driver.find_element_by_xpath('//div[@class="_3k-BhJ"][5]/table[1]/tbody/tr[5]/td[2]/ul/li')
            else :
                raise NoSuchElementException
        else :
            sec_cam = driver.find_element_by_xpath('//div[@class="_3k-BhJ"][5]/table[1]/tbody/tr[6]/td[2]/ul/li')
        flip_dict['Secondary Camera'].append(sec_cam.text)
except NoSuchElementException:
        flip_dict['Secondary Camera'].append('-')

In [73]:
try:
        if driver.find_element_by_xpath('//div[@class="_3k-BhJ"][10]/div').text != "Battery & Power Features" :   # Extracting Battery Capacity from xpath
            if driver.find_element_by_xpath('//div[@class="_3k-BhJ"][9]/div').text == "Battery & Power Features" :
                bat_chk = driver.find_element_by_xpath('//div[@class="_3k-BhJ"][9]/table/tbody/tr/td[1]')
                if bat_chk.text != "Battery Capacity" : raise NoSuchElementException
                bat_cap = driver.find_element_by_xpath('//div[@class="_3k-BhJ"][9]/table/tbody/tr/td[2]/ul/li')                
            elif driver.find_element_by_xpath('//div[@class="_3k-BhJ"][8]/div').text == "Battery & Power Features" :     
                bat_chk = driver.find_element_by_xpath('//div[@class="_3k-BhJ"][8]/table/tbody/tr/td[1]')
                if bat_chk.text != "Battery Capacity" : raise NoSuchElementException
                bat_cap = driver.find_element_by_xpath('//div[@class="_3k-BhJ"][8]/table/tbody/tr/td[2]/ul/li')
            else:
                raise NoSuchElementException
        else :
            bat_chk = driver.find_element_by_xpath('//div[@class="_3k-BhJ"][10]/table/tbody/tr/td[1]')
            if bat_chk.text != "Battery Capacity" : raise NoSuchElementException
            bat_cap = driver.find_element_by_xpath('//div[@class="_3k-BhJ"][10]/table/tbody/tr/td[2]/ul/li')                # Extracting Availability from xpath
        flip_dict['Battery Capacity'].append(bat_cap.text)
except NoSuchElementException:
        flip_dict['Battery Capacity'].append('-')

In [103]:
 try:
        if driver.find_element_by_xpath('//div[@class="_3k-BhJ"][10]/div').text != "Battery & Power Features" :
            if driver.find_element_by_xpath('//div[@class="_3k-BhJ"][9]/div').text == "Battery & Power Features" :
                bat_chk = driver.find_element_by_xpath('//div[@class="_3k-BhJ"][9]/table/tbody/tr[2]/td[1]')
                if bat_chk.text != "Battery Type" : raise NoSuchElementException
                bat_typ = driver.find_element_by_xpath('//div[@class="_3k-BhJ"][9]/table/tbody/tr[2]/td[2]/ul/li')
            elif driver.find_element_by_xpath('//div[@class="_3k-BhJ"][8]/div').text == "Battery & Power Features" :
                bat_chk = driver.find_element_by_xpath('//div[@class="_3k-BhJ"][8]/table/tbody/tr[2]/td[1]')
                if bat_chk.text != "Battery Type" : raise NoSuchElementException
                bat_typ = driver.find_element_by_xpath('//div[@class="_3k-BhJ"][8]/table/tbody/tr[2]/td[2]/ul/li')
            else:
                raise NoSuchElementException
        else :
            bat_chk = driver.find_element_by_xpath('//div[@class="_3k-BhJ"][10]/table/tbody/tr[2]/td[1]')
            if bat_chk.text != "Battery Type" : raise NoSuchElementException
            bat_typ = driver.find_element_by_xpath('//div[@class="_3k-BhJ"][10]/table/tbody/tr[2]/td[2]/ul/li')             # Extracting Battery Type from xpath
        flip_dict['Battery Type'].append(bat_typ.text)
except NoSuchElementException:
        flip_dict['Battery Type'].append('-')

In [104]:
print(len(flip_dict["Brand"]), len(flip_dict["Smartphone"]), len(flip_dict["Price"]), len(flip_dict['URL']))

1 1 1 0

In [105]:
df = pd.DataFrame.from_dict(flip_dict, orient='index')
df = df.transpose()

In [106]:
df.head(5)

,Brand,Smartphone,Colour,RAM,Storage(ROM),Primary Camera,Secondary Camera,Display Size,Display Resolution,Processor,Processor Cores,Battery Capacity,Battery Type,Price,URL
0,-,-,-,-,-,-,-,-,-,None,-,-,-,-,None
1,None,None,None,None,None,None,None,None,None,None,-,None,-,None,None
2,None,None,None,None,None,None,None,None,None,None,None,None,-,None,None

# 5

In [107]:
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

In [108]:
url = "https://www.google.co.in/maps"
driver.get(url)
time.sleep(2)

In [109]:
search = driver.find_element_by_id("searchboxinput")                       # locating search bar
search.clear()                                                             # clearing search bar
time.sleep(2)
search.send_keys("New Delhi")                                                     # entering values in search bar
button = driver.find_element_by_id("searchbox-searchbutton")               # locating search button
button.click()                                                             # clicking search button
time.sleep(3)

In [110]:
try:
    url_string = driver.current_url
    print("URL Extracted: ", url_string)
    lat_lng = re.findall(r'@(.*)data',url_string)
    if len(lat_lng):
        lat_lng_list = lat_lng[0].split(",")
        if len(lat_lng_list)>=2:
            lat = lat_lng_list[0]
            lng = lat_lng_list[1]
        print("Latitude = {}, Longitude = {}".format(lat, lng))

except Exception as e:
        print("Error: ", str(e))

URL Extracted:  https://www.google.co.in/maps/place/New+Delhi,+Delhi/@28.5933568,77.398016,13z/data=!4m5!3m4!1s0x390cfd5b347eb62d:0x52c2b7494e204dce!8m2!3d28.6139391!4d77.2090212
Latitude = 28.5933568, Longitude = 77.398016

# 6

In [111]:
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

In [112]:
url = "https://trak.in/"
driver.get(url)
time.sleep(2)

In [113]:
button = driver.find_element_by_xpath('//li[@id="menu-item-51510"]/a').get_attribute('href')
driver.get(button)

In [114]:
fund_dict = {}
fund_dict['Date'] = []
fund_dict['Startup Name'] = []
fund_dict['Industry/Vertical'] = []
fund_dict['Sub-Vertical'] = []
fund_dict['Location'] = []
fund_dict['Investor'] = []
fund_dict['Investment Type'] = []
fund_dict['Amount(in USD)'] = []

In [115]:
for i in range(48,51):
    # Date
    dt = driver.find_elements_by_xpath('//table[@id="tablepress-{}"]/tbody/tr/td[2]'.format(i))
    for d in dt:
        fund_dict['Date'].append(d.text)

    # Startup Name
    sn = driver.find_elements_by_xpath('//table[@id="tablepress-{}"]/tbody/tr/td[3]'.format(i))
    for n in sn:
        fund_dict['Startup Name'].append(n.text)
    
    # Industry/Vertical
    ind = driver.find_elements_by_xpath('//table[@id="tablepress-{}"]/tbody/tr/td[4]'.format(i))
    for n in ind:
        fund_dict['Industry/Vertical'].append(n.text)
    
    # Sub-Vertical
    sv = driver.find_elements_by_xpath('//table[@id="tablepress-{}"]/tbody/tr/td[5]'.format(i))
    for s in sv:
        fund_dict['Sub-Vertical'].append(s.text)

    # Location
    loc = driver.find_elements_by_xpath('//table[@id="tablepress-{}"]/tbody/tr/td[6]'.format(i))
    for l in loc:
        fund_dict['Location'].append(l.text)
    
    # Investor
    inv = driver.find_elements_by_xpath('//table[@id="tablepress-{}"]/tbody/tr/td[7]'.format(i))
    for n in inv:
        fund_dict['Investor'].append(n.text)
    
    # Investment Type
    invt = driver.find_elements_by_xpath('//table[@id="tablepress-{}"]/tbody/tr/td[8]'.format(i))
    for n in invt:
        fund_dict['Investment Type'].append(n.text)
    
    # Amount
    amt = driver.find_elements_by_xpath('//table[@id="tablepress-{}"]/tbody/tr/td[9]'.format(i))
    for a in amt:
        fund_dict['Amount(in USD)'].append(a.text)

In [116]:
fund_df = pd.DataFrame(fund_dict)
fund_df

,Date,Startup Name,Industry/Vertical,Sub-Vertical,Location,Investor,Investment Type,Amount(in USD)
0,15/07/2020,Flipkart,E-commerce,E-commerce,Bangalore,Walmart Inc,M&A,"1,200,000,000"
1,16/07/2020,Vedantu,EduTech,Online Tutoring,Bangalore,Coatue Management,Series D,"100,000,000"
2,16/07/2020,Crio,EduTech,Learning Platform for Developers,Bangalore,021 Capital,pre-Series A,"934,160"
3,14/07/2020,goDutch,FinTech,Group Payments,Mumbai,"Matrix India,Y Combinator, Global Founders Cap...",Seed,"1,700,000"
4,13/07/2020,Mystifly,Airfare Marketplace,"Ticketing, Airline Retailing, and Post-Ticketi...",Singapore and Bangalore,Recruit Co. Ltd.,pre-Series B,"3,300,000"
5,09/07/2020,JetSynthesys,Gaming and Entertainment,Gaming and Entertainment,Pune,Adar Poonawalla and Kris Gopalakrishnan.,Venture-Series Unknown,"400,000"
6,10/07/2020,gigIndia,Marketplace,"Crowd Sourcing, Freelance",Pune,Incubate Fund India and Beyond Next Ventures,pre-Series A,"974,200"
7,15/07/2020,PumPumPum,Automotive Rental,Used Car-leasing platform,Gurgaon,Early Adapters Syndicate,Seed,"292,800"
8,14/07/2020,FLYX,OTT Player,Streaming Social Network,New York and Delhi,"Raj Mishra, founder of AIT Global Inc",pre-Seed,"200,000"
9,13/07/2020,Open Appliances Pvt. Ltd.,Information Technology,Internet-of-Things Security Solutions,Bangalore,Unicorn India Ventures,Venture-Series Unknown,"500,000"
10,15/08/2020,Practo,HealthTech,Health care and Wellness,Bangalore,A1A Company,Series F,"32,000,000"
11,13/08/2020,Medlife,E-commerce,Online Pharmacy,Bangalore,Prasid Uno Family Trust and SC Credit Fund,,"23,000,000"
12,13/08/2020,HungerBox,FoodTech,Online Food Delivery Service,Bangalore,"One97, Sabre Partners Trust, Pratithi Investme...",Series D1,"1,560,000"
13,04/08/2020,Dunzo,Hyper-local Logistics,Online Delivery Services,Bangalore,Existing Backers,In Progress,"30,000,000"
14,11/08/2020,Terra.do,EduTech,"Online Climate School, E-learning","Stanford, California,","Stanford Angels and Entrepreneurs (India), BEE...",Seed,"1,400,000"
15,12/08/2020,Classplus,EduTech,"E-learning, Online Tutoring",Noida,Falcon Edge,In Progress,"upto 15,000,000"
16,14/08/2020,Niyo,FinTech,Financial Services,Bangalore,Niyo Solutions Inc.,,"6,000,000"
17,10/08/2020,ZestMoney,FinTech,Financial Services,Bangalore,Primrose Hills Ventures,,"10,670,000"
18,07/08/2020,FreshToHome,E-commerce,Food Delivery,Bangalore,Ascent Capital,Venture,"16,200,000"
19,13/08/2020,Eduvanz,FinTech,Financial Services,Mumbai,"Sequoia India, Unitus",Series A,"5,000,000"
20,08/09/2020,Byjuâ€™s,EduTech,Online Tutoring,Bangalore,"Silver Lake, Tiger Global, General Atlantic an...",Private Equity,"500,000,000"
21,12/09/2020,mCaffeine,Personal Care,Skincare & Haircare,Mumbai,"Amicus Capital Private Equity I LLP, Amicus Ca...",Series B,"3,000,000"
22,09/09/2020,Qshala,EduTech,Online Curiosity Platform for Kids,Bangalore,Rainmatter Capital,Angel,"370,000"
23,02/09/2020,Winzo,Online Gaming,Online Gaming,New Delhi,"Kalaari Capital Partners, IndigoEdge Managemen...",Series B,"15,500,000"
24,09/09/2020,Hippo Video,Video Customer Experience(CX) Platform,Video Customer Experience(CX) Platform,"Newark, Delaware, United States of Amercia","Alpha Wave Incubation, Exfinity Venture Partne...",Series A,"4,500,000"
25,07/09/2020,Melorra,E-commerce,Online Jewelry Store,Bangalore,"Shadow Holdings, Lightbox.",Debt Financing,"upto 8,900,000"
26,07/09/2020,1mg,E-commerce,Online Pharmacy,Gurgaon,"Gaja Capital, Tata Capital, Partners Group",In Progress,"100,000,000"
27,31/08/2020,mfine,HealthTech,On-Demand Healthcare Services,Bangalore,Caretech Pte Inc,Series B,"5,400,000"
28,31/08/2020,Apna,Human Resources,Recruitment Platform,Bangalore,Lightspeed India and Sequoia Capital India,Series A,"8,000,000"
29,03/09/2020,Railofy,Transportation,WL & RAC protection platform,Mumbai,Chiratae Ventures,Seed,"950,000"

# 7

In [117]:
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

In [118]:
url = "https://www.digit.in/"
driver.get(url)
time.sleep(2)

In [119]:
top_10=driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[4]/ul/li[4]/a")
top_10.click()

In [120]:
time.sleep(2)
#clicking on laptops option
laptops=driver.find_element_by_xpath("/html/body/div[3]/div/div/div[2]/div[5]/div[1]/div/button[2]")
laptops.click()

In [121]:
time.sleep(2)
#best gaming laptops link
best_gaming=driver.find_element_by_xpath("//div[@id='laptops']//div[3]//a")
driver.get(best_gaming.get_attribute('href'))

In [122]:
name = []
Price = []
OS = []
display = []
processor = []
HDD = []
RAM = []
weight = []
dimension = []
GPU = []

In [123]:
time.sleep(1)
#scraping names
names=driver.find_elements_by_xpath("//div[@class='right-container']/div/a/h3")
for i in names:
    name.append(i.text)

In [124]:
time.sleep(1)
#scraping operating system
os=driver.find_elements_by_xpath("//div[@class='product-detail']/div/ul/li[1]/div/div")
for i in os:
    OS.append(i.text)

In [125]:

time.sleep(1)
#scraping display
displays=driver.find_elements_by_xpath("//div[@class='product-detail']/div/ul/li[2]/div/div")
for i in displays:
    display.append(i.text)

In [126]:

time.sleep(1)
#scraping processor
processors=driver.find_elements_by_xpath("//div[@class='product-detail']/div/ul/li[3]/div/div")
for i in processors:
    processor.append(i.text)

In [127]:

time.sleep(1)
# scraping memory
memories=driver.find_elements_by_xpath("//div[@class='Spcs-details'][1]/table/tbody/tr[6]/td[3]")# extrat HDD and RAM form xpath
for i in memories:
    HDD.append(i.text.split("/")[0])
    RAM.append(i.text.split("/")[1])

In [128]:
time.sleep(1)
# scraping weight
weights=driver.find_elements_by_xpath("//div[@class='Spcs-details'][1]/table/tbody/tr[7]/td[3]")# extrat weight form xpath
for i in weights:
    weight.append(i.text)

In [129]:
time.sleep(1)
# scraping dimension
dimension=[]
dimensions=driver.find_elements_by_xpath("//div[@class='Spcs-details'][1]/table/tbody/tr[8]/td[3]") 
for i in dimensions:
    dimension.append(i.text)

In [130]:
time.sleep(1)
# scraping graphical processor
GPUs=driver.find_elements_by_xpath("//div[@class='Spcs-details'][1]/table/tbody/tr[9]/td[3]") 
for i in GPUs:
    GPU.append(i.text)

In [131]:
time.sleep(1)

#scraping price
price=driver.find_elements_by_xpath("//table[@id='summtable']//tr//td[3]")
for i in price:
    Price.append(i.text)

In [132]:
df=pd.DataFrame({"Name":name,
                "price":Price,
                "OS":OS,
                "Display":display,
                "HDD":HDD,
                 "RAM":RAM,
                "processor":processor,
                "weight":weight,
                "Dimension":dimension,
                "Graphical processor":GPU})

In [133]:
df

,Name,price,OS,Display,HDD,RAM,processor,weight,Dimension,Graphical processor
0,ALIENWARE AREA 51M R2,N/A,WINDOWS 10 HOME,"17.3"" (1920 X 1080)",1 TB SSD,16 GBGB DDR4,10TH GENERATION INTELÂ® COREâ„¢ I7-10700 | 2.90 GHZ,4.1,27.65 x 402.6 x 319.14,IntelÂ® UHD Graphics 630
1,ALIENWARE M15 R3,â‚¹341990,WINDOWS 10 HOME,"15.6"" (3840 X 2160)",1 TB SSD,16 GBGB DDR4,10TH GENERATION INTELÂ® COREâ„¢ I9-10980HK | NA,NA,NA,NA
2,ASUS ROG STRIX SCAR 15,N/A,WINDOWS 10 HOME,"15.6"" (1920 X 1080)",1 TB SSD,16 GBGB DDR4,AMD RYZENâ„¢ 9 5900HX | 3.3 GHZ,2.30,35.4 x 25.9 x 2.26,NVIDIAÂ® GeForce RTXâ„¢ 3070
3,ASUS ROG ZEPHYRUS G14,â‚¹164990,WINDOWS 10 HOME,"14"" (1920 X 1080)",1 TB SSD,16 GBGB DDR4,AMD 3RD GENERATION RYZEN 9 | 3.3 GHZ,1.65,32.5 x 22.1 x 1.8,NVIDIA GeForce RTX 2060
4,LENOVO LEGION 5I,â‚¹71990,WINDOWS 10 PRO,"15.6"" (1920 X 1080)",1 TB SSD,16 GBGB DDR4,10TH GENERATION INTELÂ® COREâ„¢ I5-10300H | 2.50 GHZ,2.3,363.06 x 259.61 x 23.57,NVIDIAÂ® GeForceÂ® GTX 1650 4GB
5,ASUS ROG ZEPHYRUS DUO 15,â‚¹185000,WINDOWS 10,"15.6"" (3840 X 1100)",512 GB SSD,4 GBGB DDR4,INTEL CORE I7 10TH GEN 10875H | NA,2.4,268.30 x 360.00 x 20.90,NVIDIA GeForce RTX 2070 Max-Q
6,ACER ASPIRE 7 GAMING,â‚¹56990,WINDOWS 10 HOME,"15.6"" (1920 X 1080)",512 GB SSD,8 GBGB DDR4,AMD RYZENâ„¢ 5-5500U HEXA-CORE | NA,2.15,2.29 x 36.3 x 25.4,NVIDIAÂ® GeForceÂ® GTX 1650

In [134]:
df.to_csv("Gaming laptops_digit.csv")

# 8.

In [43]:
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

In [44]:
url = "https://www.forbes.com/?sh=69e6b8c92254"
driver.get(url)
time.sleep(2)

In [45]:
button = driver.find_element_by_xpath("//button[@class='icon--hamburger']")
button.click()
time.sleep(1)

In [46]:
billioners = driver.find_element_by_xpath("/html/body/div[1]/header/nav/div[3]/ul/li[1]")
billioners.click()
time.sleep(1)

In [47]:
world_billioners= driver.find_element_by_xpath("/html/body/div[1]/header/nav/div[3]/ul/li[1]/div[2]/ul/li[2]/a")
world_billioners.click()
time.sleep(1)

In [48]:
Rank = [] 
Person_Name = [] 
total_net_worth = [] 
Age = []
country_of_citizenship = [] 
Source = []
industry = []

In [49]:

    #scraping rank of billionaire
    rank= driver.find_elements_by_xpath("//div[@class='rank']")
    for i in rank:
        Rank.append(i.text)
    time.sleep(1)

In [50]:
name= driver.find_elements_by_xpath("//div[@class='personName']//div")
for i in name:
        Person_Name.append(i.text)
time.sleep(1)

In [52]:
age= driver.find_elements_by_xpath("//div[@class='age']//div")
for i in age:
        Age.append(i.text)   
time.sleep(1)

In [53]:
citizenship= driver.find_elements_by_xpath("//div[@class='countryOfCitizenship']")
for i in citizenship:
        country_of_citizenship.append(i.text)
time.sleep(1)

In [54]:
source= driver.find_elements_by_xpath("//div[@class='source']")
for i in source:
        Source.append(i.text)    
time.sleep(1)

In [55]:
industries= driver.find_elements_by_xpath("//div[@class='category']//div")
for i in industries:
        industry.append(i.text)

In [56]:
net_worth= driver.find_elements_by_xpath("//div[@class='netWorth']//div[1]")
for i in net_worth:
        total_net_worth.append(i.text)
time.sleep(1)

In [62]:
        
Net_Worth = []        
for i in range(0,len(total_net_worth),2):
        Net_Worth.append(total_net_worth[i])

In [63]:
time.sleep(2)        
#creating dataframe
df=pd.DataFrame({'Rank':Rank,
                'Name':Person_Name,
                'Net Worth':Net_Worth,
                'Age':Age,
                'Country of Citizenship':country_of_citizenship,
                'Source':Source,
                'Industry':industry})

In [64]:
df

,Rank,Name,Net Worth,Age,Country of Citizenship,Source,Industry
0,1.,Jeff Bezos,$177 B,57,United States,Amazon,Technology
1,2.,Elon Musk,$151 B,49,United States,"Tesla, SpaceX",Automotive
2,3.,Bernard Arnault & family,$150 B,72,France,LVMH,Fashion & Retail
3,4.,Bill Gates,$124 B,65,United States,Microsoft,Technology
4,5.,Mark Zuckerberg,$97 B,36,United States,Facebook,Technology
...,...,...,...,...,...,...,...
195,195.,Harry Triguboff,$11.2 B,88,Australia,real estate,Real Estate
196,197.,Leonid Fedun & family,$11.1 B,65,Russia,oil,Energy
197,197.,Eyal Ofer,$11.1 B,70,Israel,"real estate, shipping",Diversified
198,197.,Evan Spiegel,$11.1 B,30,United States,Snapchat,Technology
199,200.,Luis Carlos Sarmiento,$11 B,88,Colombia,banking,Finance & Investments

# 9

In [4]:
driver=webdriver.Chrome("chromedriver.exe")
time.sleep(2)

In [5]:
url = "https://www.youtube.com/"
driver.get(url)
time.sleep(2)

In [6]:
search_bar = driver.find_element_by_id('search')
search_bar.send_keys("GOT")  #entering Video name
time.sleep(1)

In [7]:
search_btn = driver.find_element_by_id("search-icon-legacy")  
search_btn.click()
time.sleep(1)

In [8]:
link_click = driver.find_element_by_xpath("//yt-formatted-string[@class ='style-scope ytd-video-renderer']")
link_click.click()

In [9]:
for _ in range(1000):
    driver.execute_script("window.scrollBy(0,10000)")

In [10]:
comments = []
comment_time = []
Time = []
Likes = []
No_of_Likes = []

In [11]:
cm = driver.find_elements_by_id("content-text")
for i in cm:
    if i.text is None:
        comments.append("--")
    else:
        comments.append(i.text)
time.sleep(5)

In [25]:
tm = driver.find_elements_by_xpath("//a[contains(text(),'ago')]")
for i in tm:
    Time.append(i.text)

for i in range(0,len(Time),2):
    comment_time.append(Time[i])
time.sleep(5)
    
# scrape the comment likes
like = driver.find_elements_by_xpath("//span[@class='style-scope ytd-comment-action-buttons-renderer']")
for i in like:
    Likes.append(i.text)
    
for i in range(1,len(Likes),2):
    No_of_Likes.append(Likes[i])

In [26]:
time.sleep(2)
#creating dataframe
df=pd.DataFrame({'Comments':comments,
                'Time':comment_time,
                'Likes':No_of_Likes})

In [27]:
df.head(5)

Empty DataFrame
Columns: [Comments, Time, Likes]
Index: []

# 10.

In [65]:
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(3)

In [66]:
url = "https://www.hostelworld.com/"
driver.get(url)

In [70]:
search_loc = driver.find_element_by_id('search-input-field')

In [71]:
search_loc.send_keys("London")
time.sleep(2)

In [72]:
london = driver.find_element_by_xpath('/html/body/div[1]/div/div/div[1]/div[1]/div/div[2]/div[4]/div/div[2]/div/div[1]/div/div/ul/li[2]/div')
london.click()
time.sleep(2)

In [73]:
search_btn = driver.find_element_by_id('search-button')
search_btn.click()

In [74]:
Hostel_Name = []
Distance = []
overall_review = []
total_reviews = []
facilities = []
price = []
Rating = []
property_description = []

In [77]:

    
    # Hostel name
    names = driver.find_elements_by_xpath('//h2[@class="title title-6"]')
    for name in names:
        Hostel_Name.append(name.text)
    time.sleep(2)
        
    # Distance from city centre
    dis = driver.find_elements_by_xpath('//span[@class="description"]')
    for d in dis:
        Distance.append(d.text)
    time.sleep(2)
        
    # Overall Review    
    review = driver.find_elements_by_xpath('//div[@class="keyword"]//span')
    for r in review:
        overall_review.append(r.text)
    time.sleep(2)
    
    # Total No of reviews     
    t_review = driver.find_elements_by_xpath('//div[@class="reviews"]')
    for tr in t_review:
        total_reviews.append(tr.text)
    time.sleep(2)
    
    # facilities
    service = driver.find_elements_by_xpath('//div[@class="facilities-label facilities"]')
    for s in service:
        facilities.append(s.text)
    time.sleep(2)
    
    # Prices    
    prices = driver.find_elements_by_xpath('//div[@class="price-col"]')
    for p in prices:
        price.append(p.text)
    time.sleep(2)

In [78]:
time.sleep(4)        
        
# Separate  Privates_From price  and  Dorms_From price
Privates_From = []
for i in range(0,len(price),2):
    Privates_From.append(price[i])

In [79]:
time.sleep(2)

Dorms_From = []
for i in range(1,len(price),2):
    Dorms_From.append(price[i])

In [80]:
hostel_url = []

while(True):
    urls = driver.find_elements_by_xpath('//h2[@class="title title-6"]//a')
    for url in urls:
        hostel_url.append(url.get_attribute("href"))
    time.sleep(2)    
        
    try:
        next_button = driver.find_element_by_xpath('//div[@class="pagination-item pagination-next"]')
        next_button.click()
    except:
        break

In [81]:
        
Rate = []
for page in hostel_url:
    driver.get(page)
    
    # Rating
    try:
        ratings = driver.find_element_by_xpath('/html/body/div[1]/div/div/div[1]/section/div[6]/div/div[1]/div[1]/div[1]')
        Rate.append(ratings.text)
    except NoSuchElementException:
        Rate.append("No Rating")  
    time.sleep(2)

In [82]:
try:
        pd = driver.find_element_by_xpath('/html/body/div[1]/div/div/div[1]/section/div[6]/div/div[2]/div[2]/div/div[2]')
        property_description.append(pd.text)
except NoSuchElementException:
        property_description.append("No Description")

In [83]:
time.sleep(2)        
# remove extra data from Rating     
all_text = []
for i in Rate:
    all_text.append(i.split())
time.sleep(2)

In [84]:

for i in all_text:
    Rating.append(i[0])

In [86]:
a =({'Hostel Name':Hostel_Name,
                'Distance from city centre':Distance,
                'Overall Review':overall_review[3:],
                'Total Reviews':total_reviews,
                'Facilities':facilities,
                'Privates From Price':Privates_From,
                'Dorms From Price':Dorms_From,
                'Rating':Rating,
                'Property Description':property_description})

In [87]:
df = pd.DataFrame.from_dict(a, orient='index')
df = df.transpose()

In [88]:
df

,Hostel Name,Distance from city centre,Overall Review,Total Reviews,Facilities,Privates From Price,Dorms From Price,Rating,Property Description
0,St Christopher's Village,Hostel - 1.8km from city centre,Fabulous,10818 Total Reviews,Free WiFi\nFollows Covid-19 sanitation guidance,Privates From\nRs4969,Dorms From\nRs1715,8.8,No Description
1,Generator London,Hostel - 3km from city centre,Very Good,6732 Total Reviews,Free WiFi\nFollows Covid-19 sanitation guidance,Privates From\nRs8385,Dorms From\nRs2001,7.5,None
2,Safestay London Kensington Holland Park,Hostel - 5.9km from city centre,Superb,1072 Total Reviews,Free WiFi,No Privates Available,Dorms From\nRs1025,9.6,None
3,"PubLove @ The Crown, Battersea",Hostel - 4.7km from city centre,Rating,206 Total Reviews,Free WiFi\nFollows Covid-19 sanitation guidance,Privates From\nRs9801,Dorms From\nRs1656,5.6,None
4,247london Hostel and Private Rooms,Hostel - 8.2km from city centre,No Rating,443 Total Reviews,Free WiFi,Privates From\nRs5279,No Dorms Available,No,None
...,...,...,...,...,...,...,...,...,...
83,None,None,None,None,None,None,None,No,None
84,None,None,None,None,None,None,None,No,None
85,None,None,None,None,None,None,None,No,None
86,None,None,None,None,None,None,None,No,None
87,None,None,None,None,None,None,None,No,None